### ISSUE TITLE
CVE-2023-29530: Fix For PHP 7.4

### ISSUE THREAD

**Issue by sprankhub** [laminas/laminas-diactoros#142]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

For some projects, we are still on PHP 7.4. While I know that this is not perfect, and we work on updating to PHP 8, it is what it is. Currently, it looks like there is no fix for [CVE-2023-29530](https://github.com/laminas/laminas-diactoros/security/advisories/GHSA-xv3h-4844-9h36) compatible with PHP 7.4. The oldest version, which got a fix, is `2.18.1`, which only supports PHP 8. Would it also be possible to release a fixed version of `2.17.0` to still fix the issue for users currently stuck on PHP 7.4? Thanks!

**Comment by Ocramius** [comment]
PHP 7.4 no longer receives security fixes, and is therefore out of our security maintenance window.

See https://github.com/laminas/technical-steering-committee/blob/ba7fa183ec5524a8484ac77e49787d1891374bad/meetings/minutes/2020-03-02-TSC-Minutes.md?plain=1#L118-L119

We currently support fixes for PHP 8.0, PHP 8.1 and PHP 8.2, as per https://www.php.net/supported-versions.php

**Comment by Ocramius** [comment]
My tip for local maintenance is that you keep your own committed version of `laminas-diactoros` until you can move forward.

**Comment by longwave** [comment]
Speaking on behalf of the Drupal project, can I ask you to reconsider? Drupal 9, which is supported until November 2023, has a dependency on laminas-diactoros, but also still supports PHP 7.3 and 7.4. Drupal 9.4 and 9.5 currently depend on laminas-diactoros 2.14.0 due to this. If you could commit the fix to 2.14.x and release 2.14.1 that would solve the security issue for all Drupal 9 users.

Looking at the stats on Packagist, it seems that even as of last week, 2.14 is your most installed version - I suspect this is largely due to Drupal installs, but cannot be sure:

![image](https://user-images.githubusercontent.com/197817/234285653-715bfbcf-2e74-4719-91c1-cd31df30894c.png)

**Comment by Ocramius** [comment]
As for drupal itself, 10.x seems to already operate with PHP 8.1 in mind:

https://github.com/drupal/drupal/blob/8e474357682b5d0891a60c988d442694ba2f08b1/composer.json#L55-L57

9.x has `laminas/laminas-diactoros:2.14.0` locked:

https://github.com/drupal/drupal/blob/47c5f228e18b3a26476800c0baa141b56cc9d71d/composer.lock#L1131-L1133

I don't see why consumers of the drupal project couldn't perform a `composer update` there.

On a personal note, I maintain some projects that are on PHP 5.4 and PHP 5.5: I told my customers very clearly that it's totally on their end if they will get breached for a security issue, until they focus on upgrading.

I don't want to say "the policy is set in stone blah blah blah", since rules can be bent for specific cases, but really, folks: hurry up and move to maintained PHP versions. The policy is put in place precisely so that people move their bums and keep pushing for sensible maintenance schedules. 

The fact that you are on a security-**unmaintained** PHP version already makes you very vulnerable: please take a deep look at your situation over there first.

**Comment by catch56** [comment]
Drupal 10 requires PHP 8.1. Drupal 9.5 supports PHP 8+ but continues to allow installs in PHP 7.4 and PHP 7.3. This is partly because they were supported when Drupal 9.0 was released, partly because fedora, ubuntu and other distros maintain their own PHP 7.4 forks with security patches backported until their own LTS cycles run out, so in practice many installs remain secure. We do nag users who are still on 7.3/7.4 to update, we just don't stop them from updating their Drupal installs if they haven't, until they move to a new major where we set the highest reasonable minimum requirements.

We provide multiple ways to install Drupal 9.5, some allow composer update to 2.18.0, some only allow patch level updates (to more closely match the lock file) and those users are stuck until we loosen the constraint or they change their own composer setup. Although loosening the constraint will help PHP 8 users it still doesn't provide anything for 7.4 users and a release here would be useful.

**Comment by longwave** [comment]
On a related note we still support the Drupal 7.x series, and last week we put out a hotfix there because we broke compatibility with PHP _5.3_ - our users posted multiple bug reports about this. We would like users to upgrade, but it's very difficult to force them to do so!

**Comment by sprankhub** [comment]
It is not always easy to update systems like Drupal or even much bigger systems like Magento on time. There are lots of dependencies, which also need to support PHP 8, so that it works.

Additionally, please mind that there are options for long-term PHP support like [Zend Long-Term Support](https://www.zend.com/services/php-long-term-support) or [PHP LTS by Freexian](https://www.freexian.com/lts/php/). And I even believe that some distros like Debian and Ubuntu have long-term support for older PHP versions anyway.

I am not sure if insisting on "PHP 7.4 is outdated", while a lot of people still use it, is smart. We could just make the world a bit safer if we also released a security fix for a PHP 7.4 compatible version.

**Comment by weierophinney** [comment]
@catch56 The problem here is that you, an OSS project, are asking us, another OSS project, to spend our time and effort on backporting security fixes because your own OSS project has made a decision such that you continue to support versions of your software that pin to (a) older versions of our software, and (b) an already EOL version of the upstream PHP runtime.

What you are asking is for **US** to support **YOUR** software. This is no different than a commercial organization asking us to provide support. And for that, we have a policy, which @Ocramius already stated: our security window follows that of the upstream PHP runtime. This is to (a) be predictable, and (b) allow us to spend our time and effort more efficiently.

If you need LTS support for Laminas, you can try one of our [Commercial Vendors](https://getlaminas.org/commercial-vendor-program/); some of them have commercial offerings for exactly this.

**Comment by catch56** [comment]
@weierophinney god forbid open source projects should have dependencies on each other with slightly different release schedules!

**Comment by catch56** [comment]
For reference Drupal 9.5.0-alpha1 was released in February 2020 https://www.drupal.org/project/drupal/releases/9.0.0-alpha1 and your PHP support policy was decided in March 2020 https://github.com/laminas/technical-steering-committee/blob/ba7fa183ec5524a8484ac77e49787d1891374bad/meetings/minutes/2020-03-02-TSC-Minutes.md?plain=1#L118-L119 and presumably was documented/came into effect later than this.

Once we became aware of Laminas' PHP support policy we removed laminas/feed and laminas/diactoros as dependencies for Drupal 10, but it was too late to do that for Drupal 9.

**Comment by TimWolla** [comment]
FWIW: I worked together with the Guzzle and Laminas teams on company time to get this CVE fixed, writing the patch in case of Diactoros and we could not even benefit directly from the updates ourselves, because we also still need to support PHP 7.x.

So in addition to assisting the upstream projects, _because it is the right thing to do_, I also backported the patches to the versions of Guzzle and Diactoros that we ship with our application. Composer really doesn't make that hard with a git dependency: Fork the upstream repo, cherry-pick the commit in question into whatever branch you desire, fix conflicts (if any) and if you want, check that all tests still pass.

Quoting myself [from company blog](https://www.woltlab.com/article/274-php-8-2-and-woltlab-the-sensitiveparameter-attribute/): 

> Errors in our software that are caused by the use of a software library are, from the customer’s point of view, still an error in our software that must be corrected by ourselves.

**Comment by weierophinney** [comment]
We depend on other projects all the time, @catch56 . But when a scenario occurs where the dependency becomes a problem — e.g., security vulnerabilities that are not patched in versions we use, incompatibility with PHP versions we use — we then either (a) contribute to the upstream dependency (assuming this is an option), or (b) find a way to replace the dependency (usually only possible if it's an internal detail), or (c) in extreme circumstances, we fork and apply patches. This last option is kind of a nuclear option, and we will usually then release a new major that replaces it. However, if we are only looking for security patches, it's often the best option as well.

For an LTS version of a product that is ONLY getting security fixes, however, this is absolutely an option, and one I would wholly recommend. It does create a bit more effort on your part, as you have to keep an eye on security releases of the upstream project, but it guarantees for your users the continuity and security they need. It also keeps the onus on _your project_, instead of trying to offload it to the upstream dependency.

Regarding your note of the timeline of when Drupal chose Diactoros and when the Laminas LTS policy was selected, there's a LOT of mitigating factors:

- Zend Framework did not have a solid policy around LTS following the 2.4 release (the last LTS release issued); your choice to use it was based on... no policy at all, which is far worse than what we have now. (We had a security policy, but it was only around reporting vulnerabilities, not around what would be patched, or for how long.)
- Laminas had JUST been brought under the Linux Foundation in March 2020, which was when we created and announced our security policy; there was literally no time it could have been communicated earlier.

So hand waving around "hey, you changed your policy after we released" is just that, hand waving; we had no policy previously, and as the **Laminas Project**, announced it basically at the time we were formalized.

Finally, I'm going to just state this for the record: it's simply not ethical to expect an OSS upstream dependency to conform to your own LTS requirements.

If you need backports:

- Fork and apply them to your own branch, and then update to use that fork, OR
- See if you can work with a commercial vendor to do the above for you. It might cost your project money, but it may be cheaper than the _volunteer effort_ to do so yourselves.

**Comment by catch56** [comment]
@weierophinney we don't expect Laminas to do anything, this is why we stopped using it in Drupal 10, all we have done is put our reasoning across on an issue opened by somebody else. It is not unethical to ask quite a simple question.

We can of course run a fork for Drupal 9.5 and have done this for other dependencies in the past, but sometimes it is worth asking about backports to official branches vs at my count three projects already in this issue maintaining their own forks.

**Comment by longwave** [comment]
For anyone else affected by this, I have forked the code at https://github.com/longwave/laminas-diactoros, cherry-picked the fix, tagged 2.14.1 and published it on Packagist: https://packagist.org/packages/longwave/laminas-diactoros

**Comment by Xerkus** [comment]
@longwave it does not replace `^2.14`. It does `~2.14.0` and it needs to conflict with versions outside that range.

**Comment by longwave** [comment]
I have published `longwave/laminas-diactoros` 2.14.2 which replaces only `laminas/laminas-diactoros` 2.18.1 but that also allows installation on PHP 7.3 through 8.2. My justification for this is that I am bug fixing the 2.14 series, but users of `roave/security-advisories` cannot install unless I replace a currently secure version.
