### ISSUE TITLE
marshal_headers_from_sapi.php line 29

### ISSUE THREAD

**Issue by techiesflock** [laminas/laminas-diactoros#167]
marshal_headers_from_sapi.php line 29

**Comment by froschdesign** [comment]
@techiesflock 
This is the related file:

https://github.com/laminas/laminas-diactoros/blob/fe6a0c46c40dd362d354aadb8d955ade026ca6ac/src/functions/marshal_method_from_sapi.php#L1-L13

But there is no line 29, so please describe in detail what the problem is or where you see a BC break.
Thanks in advance!

**Comment by boesing** [comment]
There is no line 29 for like 2+ years, please create a more descriptive issue instead.
