### ISSUE TITLE
Conflict with zend-diactoros

### ISSUE THREAD

**Issue by danepowell** [laminas/laminas-diactoros#42]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.8.7p2

#### Summary

zend-diactoros and laminas-diactoros define the same function in the same namespace. This can lead to PHP fatal errors when both are installed in the same project. It seems like either this conflict should be resolved (i.e. by fixing the namespace or function name), or laminas-diactoros should formally declare a conflict with the older zend-diactoros in composer.json.

#### Current behavior

When running PHPUnit on our own downstream project, [an error is thrown](https://travis-ci.com/github/acquia/blt/jobs/333340883#L2207):
> PHP Fatal error:  Cannot redeclare Zend\Diactoros\createUploadedFile() (previously declared in /home/travis/build/acquia/blt/vendor/zendframework/zend-diactoros/src/functions/create_uploaded_file.php:20) in /tmp/blt-sandbox-instance/vendor/laminas/laminas-diactoros/src/functions/create_uploaded_file.legacy.php on line 19

#### How to reproduce

I haven't figured out a more minimal way to reproduce this yet, but you can see it failing in our tests above.

#### Expected behavior

laminas-diactoros and zend-diactoros should be able to be installed side-by-side without conflict, _or_ there should be a formal Composer dependency preventing them from being installed simultaneously.

**Comment by weierophinney** [comment]
laminas-diactoros packages are marked to _replace_ zend-diactoros packages; Composer does not install the original package if a package marked as a replacement is already installed. When testing prior to creating the Laminas packages, we were able to confirm this Composer behavior, which is why we chose to mark them as replacements.

So, now the question is: how did you get them to install side-by-side?

- What version of Composer did you use to install dependencies?
- What versions of (a) zend-diactoros, and (b) laminas-diactoros are installed?
- Are they being installed as project dependencies? If not, can you provide the results of `composer why`, using each package as an argument, please?

Perhaps that combination of information will allow us to attempt to reproduce the issue.

**Comment by danepowell** [comment]
Thanks a lot, that clued me in to the root cause. I think you are right that Composer should prevent this. But in our case we have symlinked a separate composer package (via a Composer path repo) into the first one. The linked package has its own vendor directory with the zend version, and somehow PHPUnit is seeing _both_ vendor directories.

I'm still not exactly sure how to fix this, but it doesn't seem like a bug in this package. Cheers.

**Comment by danepowell** [comment]
For anyone else experiencing this (since I've received support requests), you should look through your vendor directory to see where the two sets of classes (zend and laminas) are coming from. They shouldn't both be present unless you've hacked Composer, are doing some funky autoloading, or using Composer path repositories as I mentioned above.

**Comment by boesing** [comment]
@danepowell There was a bug recently fixed in composer 2.0 which also installed two versions of the same package. I've referenced it in https://github.com/composer/composer/issues/8838 but couldn't find a way of abstracting my project to a "working" example to reproduce that behavior.

Luckily, another github user provided an example which produced exactly that behavior: https://github.com/composer/composer/issues/8902

So, if you're already using composer v2 (which is not stable at this time btw), you might have a package installed which is meant to be replaced by another package (which is installed aswell).

composer fixed that issue with https://github.com/composer/composer/pull/8916.
