### ISSUE TITLE
Add other Response types as ResponseFactory methods

### ISSUE THREAD

**Issue by garrettw** [laminas/laminas-diactoros#55]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | ?
| BC Break    | no

#### Summary

I would like to be able to use `ResponseFactory` to create instances of the various `*Response` classes.

**Comment by weierophinney** [comment]
Marking as "won't fix".

The reason is because the various factories in Diactoros specifically target [PSR-17 (HTTP message factories)](https://www.php-fig.org/psr/psr-17/). Adding specialized factories to these defeats the purpose of the factories, which is to provide a standards-compliant way to produce instances without needing to rely on a specific implementation. If we have custom methods for our own purposes, then the factories are no longer mix-and-match with other PSR-17 and/or PSR-7 implementations.
